// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product-service

package it.sr.grpc.tutorial.service;

public final class ProductService {
  private ProductService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetFilmRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:it.sr.grpc.tutorial.service.GetFilmRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string filmId = 1;</code>
     * @return The filmId.
     */
    java.lang.String getFilmId();
    /**
     * <code>string filmId = 1;</code>
     * @return The bytes for filmId.
     */
    com.google.protobuf.ByteString
        getFilmIdBytes();
  }
  /**
   * Protobuf type {@code it.sr.grpc.tutorial.service.GetFilmRequest}
   */
  public static final class GetFilmRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:it.sr.grpc.tutorial.service.GetFilmRequest)
      GetFilmRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetFilmRequest.newBuilder() to construct.
    private GetFilmRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetFilmRequest() {
      filmId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetFilmRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetFilmRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              filmId_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.sr.grpc.tutorial.service.ProductService.internal_static_film_GetFilmRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.sr.grpc.tutorial.service.ProductService.internal_static_film_GetFilmRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.sr.grpc.tutorial.service.ProductService.GetFilmRequest.class, it.sr.grpc.tutorial.service.ProductService.GetFilmRequest.Builder.class);
    }

    public static final int FILMID_FIELD_NUMBER = 1;
    private volatile java.lang.Object filmId_;
    /**
     * <code>string filmId = 1;</code>
     * @return The filmId.
     */
    @java.lang.Override
    public java.lang.String getFilmId() {
      java.lang.Object ref = filmId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        filmId_ = s;
        return s;
      }
    }
    /**
     * <code>string filmId = 1;</code>
     * @return The bytes for filmId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFilmIdBytes() {
      java.lang.Object ref = filmId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filmId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(filmId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, filmId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(filmId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, filmId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof it.sr.grpc.tutorial.service.ProductService.GetFilmRequest)) {
        return super.equals(obj);
      }
      it.sr.grpc.tutorial.service.ProductService.GetFilmRequest other = (it.sr.grpc.tutorial.service.ProductService.GetFilmRequest) obj;

      if (!getFilmId()
          .equals(other.getFilmId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FILMID_FIELD_NUMBER;
      hash = (53 * hash) + getFilmId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static it.sr.grpc.tutorial.service.ProductService.GetFilmRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.sr.grpc.tutorial.service.ProductService.GetFilmRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.sr.grpc.tutorial.service.ProductService.GetFilmRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.sr.grpc.tutorial.service.ProductService.GetFilmRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.sr.grpc.tutorial.service.ProductService.GetFilmRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.sr.grpc.tutorial.service.ProductService.GetFilmRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.sr.grpc.tutorial.service.ProductService.GetFilmRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static it.sr.grpc.tutorial.service.ProductService.GetFilmRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static it.sr.grpc.tutorial.service.ProductService.GetFilmRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static it.sr.grpc.tutorial.service.ProductService.GetFilmRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static it.sr.grpc.tutorial.service.ProductService.GetFilmRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static it.sr.grpc.tutorial.service.ProductService.GetFilmRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(it.sr.grpc.tutorial.service.ProductService.GetFilmRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code it.sr.grpc.tutorial.service.GetFilmRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:it.sr.grpc.tutorial.service.GetFilmRequest)
        it.sr.grpc.tutorial.service.ProductService.GetFilmRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return it.sr.grpc.tutorial.service.ProductService.internal_static_film_GetFilmRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return it.sr.grpc.tutorial.service.ProductService.internal_static_film_GetFilmRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                it.sr.grpc.tutorial.service.ProductService.GetFilmRequest.class, it.sr.grpc.tutorial.service.ProductService.GetFilmRequest.Builder.class);
      }

      // Construct using it.sr.grpc.tutorial.service.ProductService.GetFilmRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        filmId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return it.sr.grpc.tutorial.service.ProductService.internal_static_film_GetFilmRequest_descriptor;
      }

      @java.lang.Override
      public it.sr.grpc.tutorial.service.ProductService.GetFilmRequest getDefaultInstanceForType() {
        return it.sr.grpc.tutorial.service.ProductService.GetFilmRequest.getDefaultInstance();
      }

      @java.lang.Override
      public it.sr.grpc.tutorial.service.ProductService.GetFilmRequest build() {
        it.sr.grpc.tutorial.service.ProductService.GetFilmRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public it.sr.grpc.tutorial.service.ProductService.GetFilmRequest buildPartial() {
        it.sr.grpc.tutorial.service.ProductService.GetFilmRequest result = new it.sr.grpc.tutorial.service.ProductService.GetFilmRequest(this);
        result.filmId_ = filmId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof it.sr.grpc.tutorial.service.ProductService.GetFilmRequest) {
          return mergeFrom((it.sr.grpc.tutorial.service.ProductService.GetFilmRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(it.sr.grpc.tutorial.service.ProductService.GetFilmRequest other) {
        if (other == it.sr.grpc.tutorial.service.ProductService.GetFilmRequest.getDefaultInstance()) return this;
        if (!other.getFilmId().isEmpty()) {
          filmId_ = other.filmId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        it.sr.grpc.tutorial.service.ProductService.GetFilmRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (it.sr.grpc.tutorial.service.ProductService.GetFilmRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object filmId_ = "";
      /**
       * <code>string filmId = 1;</code>
       * @return The filmId.
       */
      public java.lang.String getFilmId() {
        java.lang.Object ref = filmId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          filmId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string filmId = 1;</code>
       * @return The bytes for filmId.
       */
      public com.google.protobuf.ByteString
          getFilmIdBytes() {
        java.lang.Object ref = filmId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filmId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string filmId = 1;</code>
       * @param value The filmId to set.
       * @return This builder for chaining.
       */
      public Builder setFilmId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        filmId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string filmId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFilmId() {
        
        filmId_ = getDefaultInstance().getFilmId();
        onChanged();
        return this;
      }
      /**
       * <code>string filmId = 1;</code>
       * @param value The bytes for filmId to set.
       * @return This builder for chaining.
       */
      public Builder setFilmIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        filmId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:it.sr.grpc.tutorial.service.GetFilmRequest)
    }

    // @@protoc_insertion_point(class_scope:it.sr.grpc.tutorial.service.GetFilmRequest)
    private static final it.sr.grpc.tutorial.service.ProductService.GetFilmRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new it.sr.grpc.tutorial.service.ProductService.GetFilmRequest();
    }

    public static it.sr.grpc.tutorial.service.ProductService.GetFilmRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetFilmRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetFilmRequest>() {
      @java.lang.Override
      public GetFilmRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetFilmRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetFilmRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetFilmRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public it.sr.grpc.tutorial.service.ProductService.GetFilmRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddFilmRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:it.sr.grpc.tutorial.service.AddFilmRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string title = 1;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 1;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>string director = 2;</code>
     * @return The director.
     */
    java.lang.String getDirector();
    /**
     * <code>string director = 2;</code>
     * @return The bytes for director.
     */
    com.google.protobuf.ByteString
        getDirectorBytes();

    /**
     * <code>int32 year = 3;</code>
     * @return The year.
     */
    int getYear();
  }
  /**
   * Protobuf type {@code it.sr.grpc.tutorial.service.AddFilmRequest}
   */
  public static final class AddFilmRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:it.sr.grpc.tutorial.service.AddFilmRequest)
      AddFilmRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AddFilmRequest.newBuilder() to construct.
    private AddFilmRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddFilmRequest() {
      title_ = "";
      director_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AddFilmRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AddFilmRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              director_ = s;
              break;
            }
            case 24: {

              year_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.sr.grpc.tutorial.service.ProductService.internal_static_film_AddFilmRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.sr.grpc.tutorial.service.ProductService.internal_static_film_AddFilmRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.sr.grpc.tutorial.service.ProductService.AddFilmRequest.class, it.sr.grpc.tutorial.service.ProductService.AddFilmRequest.Builder.class);
    }

    public static final int TITLE_FIELD_NUMBER = 1;
    private volatile java.lang.Object title_;
    /**
     * <code>string title = 1;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 1;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIRECTOR_FIELD_NUMBER = 2;
    private volatile java.lang.Object director_;
    /**
     * <code>string director = 2;</code>
     * @return The director.
     */
    @java.lang.Override
    public java.lang.String getDirector() {
      java.lang.Object ref = director_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        director_ = s;
        return s;
      }
    }
    /**
     * <code>string director = 2;</code>
     * @return The bytes for director.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDirectorBytes() {
      java.lang.Object ref = director_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        director_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int YEAR_FIELD_NUMBER = 3;
    private int year_;
    /**
     * <code>int32 year = 3;</code>
     * @return The year.
     */
    @java.lang.Override
    public int getYear() {
      return year_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, title_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(director_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, director_);
      }
      if (year_ != 0) {
        output.writeInt32(3, year_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, title_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(director_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, director_);
      }
      if (year_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, year_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof it.sr.grpc.tutorial.service.ProductService.AddFilmRequest)) {
        return super.equals(obj);
      }
      it.sr.grpc.tutorial.service.ProductService.AddFilmRequest other = (it.sr.grpc.tutorial.service.ProductService.AddFilmRequest) obj;

      if (!getTitle()
          .equals(other.getTitle())) return false;
      if (!getDirector()
          .equals(other.getDirector())) return false;
      if (getYear()
          != other.getYear()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + DIRECTOR_FIELD_NUMBER;
      hash = (53 * hash) + getDirector().hashCode();
      hash = (37 * hash) + YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getYear();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static it.sr.grpc.tutorial.service.ProductService.AddFilmRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.sr.grpc.tutorial.service.ProductService.AddFilmRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.sr.grpc.tutorial.service.ProductService.AddFilmRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.sr.grpc.tutorial.service.ProductService.AddFilmRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.sr.grpc.tutorial.service.ProductService.AddFilmRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.sr.grpc.tutorial.service.ProductService.AddFilmRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.sr.grpc.tutorial.service.ProductService.AddFilmRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static it.sr.grpc.tutorial.service.ProductService.AddFilmRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static it.sr.grpc.tutorial.service.ProductService.AddFilmRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static it.sr.grpc.tutorial.service.ProductService.AddFilmRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static it.sr.grpc.tutorial.service.ProductService.AddFilmRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static it.sr.grpc.tutorial.service.ProductService.AddFilmRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(it.sr.grpc.tutorial.service.ProductService.AddFilmRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code it.sr.grpc.tutorial.service.AddFilmRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:it.sr.grpc.tutorial.service.AddFilmRequest)
        it.sr.grpc.tutorial.service.ProductService.AddFilmRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return it.sr.grpc.tutorial.service.ProductService.internal_static_film_AddFilmRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return it.sr.grpc.tutorial.service.ProductService.internal_static_film_AddFilmRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                it.sr.grpc.tutorial.service.ProductService.AddFilmRequest.class, it.sr.grpc.tutorial.service.ProductService.AddFilmRequest.Builder.class);
      }

      // Construct using it.sr.grpc.tutorial.service.ProductService.AddFilmRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        title_ = "";

        director_ = "";

        year_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return it.sr.grpc.tutorial.service.ProductService.internal_static_film_AddFilmRequest_descriptor;
      }

      @java.lang.Override
      public it.sr.grpc.tutorial.service.ProductService.AddFilmRequest getDefaultInstanceForType() {
        return it.sr.grpc.tutorial.service.ProductService.AddFilmRequest.getDefaultInstance();
      }

      @java.lang.Override
      public it.sr.grpc.tutorial.service.ProductService.AddFilmRequest build() {
        it.sr.grpc.tutorial.service.ProductService.AddFilmRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public it.sr.grpc.tutorial.service.ProductService.AddFilmRequest buildPartial() {
        it.sr.grpc.tutorial.service.ProductService.AddFilmRequest result = new it.sr.grpc.tutorial.service.ProductService.AddFilmRequest(this);
        result.title_ = title_;
        result.director_ = director_;
        result.year_ = year_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof it.sr.grpc.tutorial.service.ProductService.AddFilmRequest) {
          return mergeFrom((it.sr.grpc.tutorial.service.ProductService.AddFilmRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(it.sr.grpc.tutorial.service.ProductService.AddFilmRequest other) {
        if (other == it.sr.grpc.tutorial.service.ProductService.AddFilmRequest.getDefaultInstance()) return this;
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (!other.getDirector().isEmpty()) {
          director_ = other.director_;
          onChanged();
        }
        if (other.getYear() != 0) {
          setYear(other.getYear());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        it.sr.grpc.tutorial.service.ProductService.AddFilmRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (it.sr.grpc.tutorial.service.ProductService.AddFilmRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 1;</code>
       * @return The title.
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 1;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 1;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 1;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object director_ = "";
      /**
       * <code>string director = 2;</code>
       * @return The director.
       */
      public java.lang.String getDirector() {
        java.lang.Object ref = director_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          director_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string director = 2;</code>
       * @return The bytes for director.
       */
      public com.google.protobuf.ByteString
          getDirectorBytes() {
        java.lang.Object ref = director_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          director_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string director = 2;</code>
       * @param value The director to set.
       * @return This builder for chaining.
       */
      public Builder setDirector(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        director_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string director = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDirector() {
        
        director_ = getDefaultInstance().getDirector();
        onChanged();
        return this;
      }
      /**
       * <code>string director = 2;</code>
       * @param value The bytes for director to set.
       * @return This builder for chaining.
       */
      public Builder setDirectorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        director_ = value;
        onChanged();
        return this;
      }

      private int year_ ;
      /**
       * <code>int32 year = 3;</code>
       * @return The year.
       */
      @java.lang.Override
      public int getYear() {
        return year_;
      }
      /**
       * <code>int32 year = 3;</code>
       * @param value The year to set.
       * @return This builder for chaining.
       */
      public Builder setYear(int value) {
        
        year_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 year = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearYear() {
        
        year_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:it.sr.grpc.tutorial.service.AddFilmRequest)
    }

    // @@protoc_insertion_point(class_scope:it.sr.grpc.tutorial.service.AddFilmRequest)
    private static final it.sr.grpc.tutorial.service.ProductService.AddFilmRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new it.sr.grpc.tutorial.service.ProductService.AddFilmRequest();
    }

    public static it.sr.grpc.tutorial.service.ProductService.AddFilmRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddFilmRequest>
        PARSER = new com.google.protobuf.AbstractParser<AddFilmRequest>() {
      @java.lang.Override
      public AddFilmRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddFilmRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AddFilmRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddFilmRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public it.sr.grpc.tutorial.service.ProductService.AddFilmRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FilmResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:it.sr.grpc.tutorial.service.FilmResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string title = 1;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 1;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>string director = 2;</code>
     * @return The director.
     */
    java.lang.String getDirector();
    /**
     * <code>string director = 2;</code>
     * @return The bytes for director.
     */
    com.google.protobuf.ByteString
        getDirectorBytes();

    /**
     * <code>int32 year = 3;</code>
     * @return The year.
     */
    int getYear();
  }
  /**
   * Protobuf type {@code it.sr.grpc.tutorial.service.FilmResponse}
   */
  public static final class FilmResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:it.sr.grpc.tutorial.service.FilmResponse)
      FilmResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FilmResponse.newBuilder() to construct.
    private FilmResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FilmResponse() {
      title_ = "";
      director_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FilmResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FilmResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              director_ = s;
              break;
            }
            case 24: {

              year_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return it.sr.grpc.tutorial.service.ProductService.internal_static_film_FilmResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return it.sr.grpc.tutorial.service.ProductService.internal_static_film_FilmResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              it.sr.grpc.tutorial.service.ProductService.FilmResponse.class, it.sr.grpc.tutorial.service.ProductService.FilmResponse.Builder.class);
    }

    public static final int TITLE_FIELD_NUMBER = 1;
    private volatile java.lang.Object title_;
    /**
     * <code>string title = 1;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 1;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIRECTOR_FIELD_NUMBER = 2;
    private volatile java.lang.Object director_;
    /**
     * <code>string director = 2;</code>
     * @return The director.
     */
    @java.lang.Override
    public java.lang.String getDirector() {
      java.lang.Object ref = director_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        director_ = s;
        return s;
      }
    }
    /**
     * <code>string director = 2;</code>
     * @return The bytes for director.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDirectorBytes() {
      java.lang.Object ref = director_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        director_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int YEAR_FIELD_NUMBER = 3;
    private int year_;
    /**
     * <code>int32 year = 3;</code>
     * @return The year.
     */
    @java.lang.Override
    public int getYear() {
      return year_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, title_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(director_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, director_);
      }
      if (year_ != 0) {
        output.writeInt32(3, year_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, title_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(director_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, director_);
      }
      if (year_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, year_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof it.sr.grpc.tutorial.service.ProductService.FilmResponse)) {
        return super.equals(obj);
      }
      it.sr.grpc.tutorial.service.ProductService.FilmResponse other = (it.sr.grpc.tutorial.service.ProductService.FilmResponse) obj;

      if (!getTitle()
          .equals(other.getTitle())) return false;
      if (!getDirector()
          .equals(other.getDirector())) return false;
      if (getYear()
          != other.getYear()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + DIRECTOR_FIELD_NUMBER;
      hash = (53 * hash) + getDirector().hashCode();
      hash = (37 * hash) + YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getYear();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static it.sr.grpc.tutorial.service.ProductService.FilmResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.sr.grpc.tutorial.service.ProductService.FilmResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.sr.grpc.tutorial.service.ProductService.FilmResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.sr.grpc.tutorial.service.ProductService.FilmResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.sr.grpc.tutorial.service.ProductService.FilmResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static it.sr.grpc.tutorial.service.ProductService.FilmResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static it.sr.grpc.tutorial.service.ProductService.FilmResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static it.sr.grpc.tutorial.service.ProductService.FilmResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static it.sr.grpc.tutorial.service.ProductService.FilmResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static it.sr.grpc.tutorial.service.ProductService.FilmResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static it.sr.grpc.tutorial.service.ProductService.FilmResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static it.sr.grpc.tutorial.service.ProductService.FilmResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(it.sr.grpc.tutorial.service.ProductService.FilmResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code it.sr.grpc.tutorial.service.FilmResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:it.sr.grpc.tutorial.service.FilmResponse)
        it.sr.grpc.tutorial.service.ProductService.FilmResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return it.sr.grpc.tutorial.service.ProductService.internal_static_film_FilmResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return it.sr.grpc.tutorial.service.ProductService.internal_static_film_FilmResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                it.sr.grpc.tutorial.service.ProductService.FilmResponse.class, it.sr.grpc.tutorial.service.ProductService.FilmResponse.Builder.class);
      }

      // Construct using it.sr.grpc.tutorial.service.ProductService.FilmResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        title_ = "";

        director_ = "";

        year_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return it.sr.grpc.tutorial.service.ProductService.internal_static_film_FilmResponse_descriptor;
      }

      @java.lang.Override
      public it.sr.grpc.tutorial.service.ProductService.FilmResponse getDefaultInstanceForType() {
        return it.sr.grpc.tutorial.service.ProductService.FilmResponse.getDefaultInstance();
      }

      @java.lang.Override
      public it.sr.grpc.tutorial.service.ProductService.FilmResponse build() {
        it.sr.grpc.tutorial.service.ProductService.FilmResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public it.sr.grpc.tutorial.service.ProductService.FilmResponse buildPartial() {
        it.sr.grpc.tutorial.service.ProductService.FilmResponse result = new it.sr.grpc.tutorial.service.ProductService.FilmResponse(this);
        result.title_ = title_;
        result.director_ = director_;
        result.year_ = year_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof it.sr.grpc.tutorial.service.ProductService.FilmResponse) {
          return mergeFrom((it.sr.grpc.tutorial.service.ProductService.FilmResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(it.sr.grpc.tutorial.service.ProductService.FilmResponse other) {
        if (other == it.sr.grpc.tutorial.service.ProductService.FilmResponse.getDefaultInstance()) return this;
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (!other.getDirector().isEmpty()) {
          director_ = other.director_;
          onChanged();
        }
        if (other.getYear() != 0) {
          setYear(other.getYear());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        it.sr.grpc.tutorial.service.ProductService.FilmResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (it.sr.grpc.tutorial.service.ProductService.FilmResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 1;</code>
       * @return The title.
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 1;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 1;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 1;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object director_ = "";
      /**
       * <code>string director = 2;</code>
       * @return The director.
       */
      public java.lang.String getDirector() {
        java.lang.Object ref = director_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          director_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string director = 2;</code>
       * @return The bytes for director.
       */
      public com.google.protobuf.ByteString
          getDirectorBytes() {
        java.lang.Object ref = director_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          director_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string director = 2;</code>
       * @param value The director to set.
       * @return This builder for chaining.
       */
      public Builder setDirector(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        director_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string director = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDirector() {
        
        director_ = getDefaultInstance().getDirector();
        onChanged();
        return this;
      }
      /**
       * <code>string director = 2;</code>
       * @param value The bytes for director to set.
       * @return This builder for chaining.
       */
      public Builder setDirectorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        director_ = value;
        onChanged();
        return this;
      }

      private int year_ ;
      /**
       * <code>int32 year = 3;</code>
       * @return The year.
       */
      @java.lang.Override
      public int getYear() {
        return year_;
      }
      /**
       * <code>int32 year = 3;</code>
       * @param value The year to set.
       * @return This builder for chaining.
       */
      public Builder setYear(int value) {
        
        year_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 year = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearYear() {
        
        year_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:it.sr.grpc.tutorial.service.FilmResponse)
    }

    // @@protoc_insertion_point(class_scope:it.sr.grpc.tutorial.service.FilmResponse)
    private static final it.sr.grpc.tutorial.service.ProductService.FilmResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new it.sr.grpc.tutorial.service.ProductService.FilmResponse();
    }

    public static it.sr.grpc.tutorial.service.ProductService.FilmResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FilmResponse>
        PARSER = new com.google.protobuf.AbstractParser<FilmResponse>() {
      @java.lang.Override
      public FilmResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FilmResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FilmResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FilmResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public it.sr.grpc.tutorial.service.ProductService.FilmResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_film_GetFilmRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_film_GetFilmRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_film_AddFilmRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_film_AddFilmRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_film_FilmResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_film_FilmResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017product-service\022\004film\" \n\016GetFilmReques" +
      "t\022\016\n\006filmId\030\001 \001(\t\"?\n\016AddFilmRequest\022\r\n\005t" +
      "itle\030\001 \001(\t\022\020\n\010director\030\002 \001(\t\022\014\n\004year\030\003 \001" +
      "(\005\"=\n\014FilmResponse\022\r\n\005title\030\001 \001(\t\022\020\n\010dir" +
      "ector\030\002 \001(\t\022\014\n\004year\030\003 \001(\0052{\n\013FilmService" +
      "\0225\n\007GetFilm\022\024.it.sr.grpc.tutorial.service.GetFilmRequest\032\022.film" +
      ".FilmResponse\"\000\0225\n\007AddFilm\022\024.it.sr.grpc.tutorial.service.AddFil" +
      "mRequest\032\022.it.sr.grpc.tutorial.service.FilmResponse\"\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_film_GetFilmRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_film_GetFilmRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_film_GetFilmRequest_descriptor,
        new java.lang.String[] { "FilmId", });
    internal_static_film_AddFilmRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_film_AddFilmRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_film_AddFilmRequest_descriptor,
        new java.lang.String[] { "Title", "Director", "Year", });
    internal_static_film_FilmResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_film_FilmResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_film_FilmResponse_descriptor,
        new java.lang.String[] { "Title", "Director", "Year", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
